# -*- coding: utf-8 -*-
"""4080N024_1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N8I3DkXrF2aze-1qwt1LZ6XIqP7ee-xh
"""

a = eval(input("B's name："))
a

b=a+1
b